Insert into items values('chicken', 'food' , 100 , 0 , 200);
Insert into items values('indomie', 'snacks' , 5 , 0 , 200);
Insert into items values('tuna', 'food' , 40 , 0.2 , 50);
Insert into items values('ketchup', 'extras' , 20 , 0.15 , 100);
Insert into items values('domty cheese', 'cheese' , 30 , 0 , 200);
Insert into items values('presdinet cheese', 'cheese' , 40 , 0 , 100);
Insert into items values('mozarella cheese', 'cheese' , 60 , 0.3 , 200);
Insert into items values('lamar milk', 'milk' , 40 , 0 , 100);
Insert into items values('almarai milk', 'milk' , 20 , 0 , 100);
Insert into items values('tomato(1k)', 'vegetables' , 20 , 0 , 50);
Insert into items values('lemon(1k)', 'vegetables' , 35 , 0 , 50);
Insert into items values('potato(1k)', 'vegetables' , 30 , 0 , 60);
Insert into items values('strawberry(1k)', 'fruit' , 20 , 0.05 , 50);
Insert into items values('orange(1k)', 'fruit' , 7 , 0 , 50);
Insert into items values('avocado(1k)', 'fruit' , 40 , 0.2 , 50);
Insert into items values('beef(1k)', 'food' , 125 , 0 , 100);
Insert into items values('kitkat', 'snacks' , 11 , 0 , 300);
Insert into items values('cadbury', 'snacks' , 12 , 0 , 300);
Insert into items values('chips', 'snacks' , 5 , 0 , 200);
Insert into items values('cupcake', 'snacks' , 3 , 0 , 50);
Insert into items values('marshmello', 'snacks' , 30 , 0 , 300);
Insert into items values('croissants', 'snacks' , 5 , 0 , 100);
Insert into items values('cola diet', 'snacks' , 6 , 0 , 300);
Insert into items values('shampoo', 'haircare' , 50 , 0 , 300);
Insert into items values('hair oil', 'haircare' , 150 , 0 , 300);
Insert into items values('rivoli soap', 'soap' , 20 , 0.2 , 300);
Insert into items values('dettol soap', 'soap' , 50 , 0.2 , 200);
Insert into items values('almaleka pasta', 'pasta' , 7 , 0 , 300);
Insert into items values('italiano pasta', 'pasta' , 12 , 0 , 100);
Insert into items values('regina pasta', 'pasta' , 12 , 0 , 250);
